## CH1 벡터, 행렬, 배열

### 1.1 벡터 만들기

In [1]:
import numpy as np

In [3]:
# 행이 하나인 벡터
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [6]:
# 열이 하나인 벡터
vector_col = np.array([[1],
                       [2],
                       [3]])
vector_col

array([[1],
       [2],
       [3]])

넘파이 배열은 ndarray 클래스의 객체이다.  
즉, type이 ndarray

In [7]:
print(type(vector_col))

<class 'numpy.ndarray'>


In [9]:
bad_way = np.ndarray((3,))
bad_way

array([4.67460539e-310, 0.00000000e+000, 4.67460339e-310])

In [11]:
new_row = np.asarray([1,2,3])
new_row

array([1, 2, 3])

In [14]:
# asarray는 새로운 배열을 만들지 않는다.
new_row = np.asarray(vector_row)
new_row is vector_row

True

In [16]:
# array는 배열이 입력되면 새로운 배열을 만든다.
new_row = np.array(vector_row)
new_row is vector_row

False

In [17]:
new_row = vector_row.copy()
new_row is vector_row

False

### 1.2 행렬 만들기

In [20]:
# array로 행렬 만들기
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [22]:
# 이 구조는 추천X 
# array가 넘파이 표준 데이터 구조
# 대부분 넘파이 함수는 행렬 객체가 아니라 배열을 반환한다.

matrix_object = np.mat([[1,2],
                        [1,2],
                        [1,2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [23]:
# 임의의 값 채워진 배열 만들기 
empty_matrix = np.empty((3,2))
empty_matrix

array([[5.e-324, 1.e-323],
       [5.e-324, 1.e-323],
       [5.e-324, 1.e-323]])

In [24]:
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
one_matrix = np.ones((3,2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
seven_matrix = np.full((3,2),7)
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

### 1.3 희소 행렬 만들기
데이터에 0이 아닌 값이 매우 적을 때 이를 효율적으로 표현하고 싶음.  

In [28]:
import numpy as np
from scipy import sparse

In [29]:
# 행렬 만들기
matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [32]:
# csr 행렬 만들기
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


희소 행렬은 0이 아닌 원소만 저장한다.  
csr(compressed sparse row)행렬에서 (1,1), (2,0)은 0이 아닌 값인 1과 3의 인덱스를 각각 나타낸다.  
즉, 1은 두번째 행의 두 번째 열에 있는 원소이다.  

In [33]:
sev_matrix_sparse = sparse.csr_matrix(seven_matrix)
print(sev_matrix_sparse)

  (0, 0)	7
  (0, 1)	7
  (1, 0)	7
  (1, 1)	7
  (2, 0)	7
  (2, 1)	7


In [34]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0,0,0,0,0],
                         [3,0,0,0,0,0,0,0,0,0,0,0,0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [35]:
# 희소행렬을 밀집행렬로
print(matrix_large_sparse.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0 0 0 0]]


In [36]:
# np.matrix 객체로 반환
matrix_large_sparse.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 1.4 원소 선택하기

In [46]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [47]:
vector[2]

3

In [48]:
matrix[1,1]

5

In [49]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [50]:
# 첫번째, 두번째 행과 모든 열 선택
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# 첫번째, 세번째 행 선택
matrix[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [54]:
# (0,1),(2,0) 위치 원소 선택
matrix[[0,1],[2,0]]

array([3, 4])

In [56]:
mask = matrix > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [58]:
matrix[mask]

array([6, 7, 8, 9])

### 1.5 행렬 정보 확인하기
행렬 크기, 원소 개수, 차원

In [60]:
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [61]:
matrix.shape

(3, 4)

In [62]:
# 원소의 개수 (행*열)
matrix.size

12

In [64]:
# 차원 수
matrix.ndim

2

In [65]:
print(matrix.dtype)

int64


In [66]:
# 원소 하나가 차지하는 바이트 크기
print(matrix.itemsize)

8


In [67]:
# 배열 전체가 차지하는 바이트 크기
print(matrix.nbytes)

96


### 1.6 백터화 연산 적용하기
배열의 원소에 어떤 함수를 적용하고 싶다.

In [68]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [69]:
# 100을 더하는 함수를 만든다.
add_100 = lambda i: i+100

In [71]:
vectorized_add_100 = np.vectorize(add_100)

In [73]:
# 행렬의 모든 원소에 함수를 적용한다.
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [74]:
# 브로드캐스팅: 넘파일 배열은 차원이 달라도 배열 간의 연산을 수행할 수 있다.
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [77]:
np.array([100, 200, 300]).shape

(3,)

In [79]:
np.array([[100],[200],[300]]).shape

(3, 1)

In [75]:
# (3,3) 크기 행렬에 (3,)인 벡터를 더하면 (1,3) 크기가 된 다음 행을 따라 반복된다.

matrix + [100, 200, 300]

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [80]:
# (3,3) 크기 행렬에 (3,1) 크기 벡터를 더하면 열을 따라 반복된다.
matrix + [[100],[200],[300]]

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

### 1.7 최댓값, 최솟값 찾기

In [81]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [82]:
np.max(matrix)

9

In [83]:
np.min(matrix)

1

In [84]:
# 각 열에서 최댓값
np.max(matrix, axis = 0)

array([7, 8, 9])

In [85]:
# 각 행에서 최댓값
np.max(matrix, axis = 1)

array([3, 6, 9])

### 1.8 평균, 분산, 표준편차 계산하기

In [86]:
np.mean(matrix)

5.0

In [87]:
np.var(matrix)

6.666666666666667

In [88]:
np.std(matrix)

2.581988897471611

In [89]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

### 1.9 배열 크기 바꾸기

In [90]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

In [91]:
matrix.reshape(2,6) 
# 원소의 개수는 동일하게!

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

reshape에 사용할 수 있는 매개변수 -1은 가능한 많이라는 뜻으로 사용된다.  
`reshape(1,-1)`은 행 하나에 열은 가능한 많게라는 의미이다.

In [93]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [94]:
# 정수 하나 입력하면 그 길이의 1차원 배열을 반환한다.
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
# 1차원 배열로 바꿔준다.
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.10 벡터나 행렬 전치하기

In [97]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [99]:
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [100]:
# 이렇게 해줘야 전치 가능
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [101]:
matrix.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### 1.12 행렬의 랭크 구하기

In [103]:
matrix = np.array([[1,1,1],
                   [1,1,10],
                   [1,1,15]])

In [104]:
np.linalg.matrix_rank(matrix)

2

### 1.13 행렬식 계산하기 (determinant)

In [107]:
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,8,9]])

In [108]:
np.linalg.det(matrix)

0.0

### 1.14 행렬의 대각원소 추출하기

In [109]:
matrix.diagonal()

array([1, 4, 9])

In [120]:
# 주 대각선에서 벗어난 대각원소 반환
# 주 대각선 하나 위의 대각원소
matrix.diagonal(offset=1)

array([2, 6])

In [121]:
# 주 대각선 하나 아래의 대각원소
matrix.diagonal(offset=-1)

array([2, 8])

### 1.15 행렬의 대각합 계산하기

In [122]:
matrix.trace()

14

In [123]:
sum(matrix.diagonal())

14

### 1.16 고유값 고유벡터 찾기

In [124]:
matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])

In [125]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [126]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [127]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### 1.17 점곱 계산하기 dot product

In [128]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [129]:
np.dot(vector_a, vector_b)

32

In [130]:
vector_a @ vector_b

32

### 1.18 행렬 덧셈과 뺄셈

In [131]:
matrix_a = np.array([[1,1,1],
                     [1,1,1],
                     [1,1,2]])
matrix_b = np.array([[1,3,1],
                     [1,3,1],
                     [1,3,8]])

In [132]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [133]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [134]:
matrix_a+matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

### 1.19 행렬 곱셈

In [135]:
matrix_a = np.array([[1,1],
                     [1,2]])
matrix_b = np.array([[1,3],
                     [1,2]])

In [136]:
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [137]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [138]:
# 원소별 곱셈
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

### 1.20 역행렬

In [139]:
matrix = np.array([[1,4],
                   [2,5]])

In [140]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [141]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

### 1.21 난수 생성하기

In [145]:
np.random.seed(0)

In [143]:
# 0.0과 1.0 사이에서 세개의 실수 난수를 생성
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [146]:
# 1,10 사이에서 세개의 정수 난수
np.random.randint(1,11,3)

array([6, 1, 4])

In [147]:
# 평균 0 표준편차 1인 정규분포에서 난수
np.random.normal(0.0, 1.0, 3)

array([ 0.07085926,  0.07304142, -1.42232584])